### ISSUE TITLE
Exclude file greater than 300MB from getting uploaded

### ISSUE THREAD

**Issue by jsetton** [thebigmunch/google-music-scripts#20]
I recently migrated from gmusicapi-scripts and I noticed that the exclude file paths matching pattern argument wasn't ported over. I was actually using that parameter to exclude all files greater than 300MB from my music library when syncing due to the [Google Music's file size limitation](https://support.google.com/googleplaymusic/answer/1143668?hl=en&visit_id=636826011000922972-3520042830&rd=1).

Right now, gms will try to upload the file and fail in the end. Why not just skip these files to save time and bandwidth?

`
[2019-01-08 22:29:42] (1/1) Failed -- foobar.mp3 | {'errorMessage': {'reason': 'REQUEST_REJECTED', 'additionalInfo': {'uploader_service.GoogleRupioAdditionalInfo': {'completionInfo': {'status': 'REJECTED', 'customerSpecificInfo': {'ResponseCode': 413}}, 'requestRejectedInfo': {'reasonDescription': 'upload_too_large'}}}, 'upload_id': 'foobar'}}
`

**Comment by thebigmunch** [comment]
That depends on when it's failing. If it's failing after the metadata call as I'd hope and expect, then there's really nothing much to save. It would be failing before any time/processing is wasted creating a sample and isn't actually getting to the upload step. Unfortunately, that magnificent mess of a response (yay Google) says it makes it all the way to uploading.

The problem becomes, the restriction is for the uploaded MP3 file to be no greater than 300 MiB. We can't know if non-MP3 files will be over 300 MiB as MP3 until we've already transcoded them, which is done right before making the actual upload call. And it wouldn't make sense to transcode any earlier in case no upload is needed at all. But, we can still check the size after transcoding so as not to make the upload call. Though I generally think it ugly/cluttered to have different fail points for different formats, I could probably fail early for MP3s as well as checking right before the upload call for non-MP3s.

Excluding them before it gets to the upload process entirely isn't great for one major reason, it would prevent users from getting that information about those files. I would add a nicer output for this case like I do with already existing files.

PS The ability to exclude filepaths may be coming back.

**Comment by jsetton** [comment]
I agree with you can't predict the final size on non-MP3 files that need to be transcoded although maybe a maximum compression ratio could be checked for that case scenario. I was just thinking of adding a preliminary size check just after the file could be transcoded and before it gets uploaded to Google. I made the below change to accommodate my need, as my music library is only composed of MP3 files with bitrate up to 320 kbps.

https://github.com/jsetton/google-music/commit/fe984bbf99c49709cc7480589954fb10113ce117

**Comment by thebigmunch** [comment]
I definitely don't see a need to set it as a constant, so I wouldn't do that.

I'm also pretty sure that by 300 MB, Google actually means 300 MiB. That would make the number you're using incorrect. But that would require some testing to confirm.

**Comment by jsetton** [comment]
You are indeed correct. It is a 300 MiB restriction. I was able to confirm per my test results below. I also updated my change based on your feedback.

https://github.com/jsetton/google-music/commit/ab4fab4bc1b962f15f85bf1f82c234bc069f370d

```
$ stat -c "%s %n" test1.mp3 test2.mp3
314569085 test1.mp3
314592909 test2.mp3

$ gms upload test1.mp3 test2.mp3
[2019-01-09 19:14:15] Logging in to Google Music
[2019-01-09 19:14:17] Loading local songs
[2019-01-09 19:14:17] Uploading 2 songs to Google Music
[2019-01-09 19:21:39] (1/2) Uploaded -- /tmp/test1.mp3 (*****)
[2019-01-09 19:28:49] (2/2) Failed -- /tmp/test2.mp3 | {'errorMessage': {'reason': 'REQUEST_REJECTED', 'additionalInfo': {'uploader_service.GoogleRupioAdditionalInfo': {'completionInfo': {'status': 'REJECTED', 'customerSpecificInfo': {'ResponseCode': 413}}, 'requestRejectedInfo': {'reasonDescription': 'upload_too_large'}}}, 'upload_id': '*****'}}
[2019-01-09 19:28:49] All done!
```

**Comment by thebigmunch** [comment]
PS A hint for making units for file sizes and such much clearer for people reading code: ``300 * 1024 * 1024`` makes it simple for people to see quite simply that it's 300 MiB, even without comments. Even if you didn't want to use multiplication in a situation, Python 3.6+ (which my libraries are restricted to) allow you to use underscores in numeric literals as visual separators. ``314_572_800`` is nicer than ``314572800``.

**Comment by jsetton** [comment]
Thanks for the advice. I updated my repository. Anyway, I was just sharing the changes I made to accommodate my need. I wasn't sure if this is what you had in mind to resolve this issue. I can submit a PR if you want me to.

**Comment by thebigmunch** [comment]
Released now.
