### ISSUE TITLE
mp3tags are weirdly or not transmitted

### ISSUE THREAD

**Issue by fdw** [thebigmunch/google-music-scripts#23]
Hi, it's me again - sorry!

After syncing my music with Google Music, I noticed that
* the date tag not transmitted
* the artist tag is mangled: I use `0`-seperated multiple values to have several artists for one file, in accordance with the standard. However, I think Google Music only supports one entry. For me, a valid way to implement it would be to just the first artist found, or even to replace the `0`-separator with a ` & `. However, it seems that the whole string including the `0` is transmitted, which results in ugly special chars.

Thank you so much for your work!

**Comment by thebigmunch** [comment]
Using the first value from the list is exactly what's done.

By date, do you mean year? The year tag is done properly for my MP3 uploads.

By 0, do you mean null? There'll be a difference. How are you creating these tags that you're dealing with the separators yourself? I can't think of any editors off the top of my head that actually support adding multiple values for fields. Are you sure you're doing something that's supported?

**Comment by thebigmunch** [comment]
PS Feel free to send me files. There are some other possibilities, like some of the information is in ID3v1 tag and other is in ID3v2. In ``audio-metadata``, I've chosen to only read ID3v1 info if an ID3v2 tag isn't present. I believe this is also what mutagen does.

**Comment by thebigmunch** [comment]
PPS ID3v2.3 actually specifies using ``/`` as the separator, which I'd forgotten (ID3 is fairly awful). I don't have that supported in ``audio-metadata``, but I could possibly add that.

**Comment by fdw** [comment]
Thank you for the answers!
I'm using [Quod Libet](https://quodlibet.readthedocs.io/en/latest/) to tag my files, which uses mutagen. As far as I know it supports ID3v2.4 and the 0 byte separator. I'm quite sure I removed all ID3v1 tags.

Regarding the date field, I will check again if it really happened with the newly synced files.

**Comment by fdw** [comment]
I just checked, and none of the newly uploaded files have a date set, even though the originals contain one. The relevant tag is `TDRC` (selected by mutagen) - maybe you use another one?

**Comment by thebigmunch** [comment]
If you were editing existing tags that were v2.3, mutagen at least won't upgrade them unless specified. So, if you wanted to check on that or email me a file to look at it. As for supporting the ``/`` separator from v2.3, that's gonna be a no. mutagen doesn't seem to either. It was a terrible idea as there are more than a few bands with that character in their name.

**Comment by thebigmunch** [comment]
Since the ``TDRC`` frame difference is likely one that will come up again, I think I may hack in a temp fix for it.

If I add the ``'TDRC': ID3v2YearFrame`` part as above to ``audio-metadata`` and have ``google-music-proto`` check for that as well as the prettier ``'date'``, it should work until I make the larger changes.

**Comment by fdw** [comment]
Okay,  this is much larger than I anticipated. I can understand it if you don't want to support a rarely-used format. Also, I agree that `/` as a separator is a bad idea adn should not be supported.

I will email you a test file that I tagged using Quod Libet. Maybe this will help sort out the versions :)

**Comment by thebigmunch** [comment]
Thanks for sending the test file. I'll have an ``audio-metadata`` bugfix release out to properly support multiple value text frames as well as adding the ``TDRC`` frame shortly. Then I'll make a release of ``google-music-proto`` that checks for ``TDRC`` as well as the 'easy' ``date`` key for the year to send to Google. Then you should be well sorted for your files.

Thanks again for putting my libraries through their paces and letting me know when they fail.

**Comment by fdw** [comment]
I don't know how to appropriatly thank you. You are great 😄

**Comment by thebigmunch** [comment]
Oh yeah. I probably should have mentioned the easiest way to create a simple test file in case you didn't want to send the ones you were actually working with: ``ffmpeg -f lavfi -i anullsrc -t 1 test.mp3``. That creates a 1 second silent MP3 file. Might come in handy in the future.

**Comment by thebigmunch** [comment]
Or hold on that until I fix a condition I forgot to take into account : P

**Comment by thebigmunch** [comment]
And, fixed.

Actually, I just forgot to pass the encoding on to a function call in ``audio-metadata`` : (

Missed it because the test files I used all used the default encoding, but I happened to be uploading an MP3 (which make up a very small portion of my music collection) this afternoon that used a different encoding : )

**Comment by fdw** [comment]
I just ran it, and yes, everything works perfectly! Thank you so much!
