### ISSUE TITLE
Base path for sync download created incorrectly in some cases after pathlib changes

### ISSUE THREAD

**Issue by CharonIDRONES** [thebigmunch/google-music-scripts#29]
When using 'gms sync down' it will verify if the the files are present in the current directory and not bring them down if present. If you use 'gms sync down -o' (e.g. gms sync down '+artist[Artist]+album[Album]' -o %artist%/%album%/%track) then it will redownload the files each time regardless if they're present.

**Comment by thebigmunch** [comment]
Yeah, this seems to be a regression with my move to using pathlib. Should be fairly easily fixable, but I found some other more pressing things that needed correcting with the template system along the way.

**Comment by thebigmunch** [comment]
Would you mind sending me some of those files that exhibit this (just 2 would be enough) so I can test with them. Just want to make sure there isn't something different that isn't accounted for.

You can attach them to a comment here, link them here, or attach/link them in email (found on my user page).
