### ISSUE TITLE
keep device_id somewhere

### ISSUE THREAD

**Issue by diraimondo** [thebigmunch/google-music-scripts#4]
Using gms it would be nice to have it to memorize somewhere a default device_id. google-music already memorize in ~/.local/share/google-music/ authentication tokens. It would be great if, instead of the mac address derivated one, one could keep (maybe in the same file) a further field `device_id` to be automatically used if nothing is specified in the command-line.

**Comment by thebigmunch** [comment]
Yeah, I've been thinking about that as part of a config file for ``google-music-scripts`` and/or ``google-music``. Just haven't gotten around to thinking it through yet. Hopefully soon.

**Comment by thebigmunch** [comment]
I have a bigger debate in my head about using ``device`` vs ``device_id``, especially in ``google-music``. But I can put that off for later. Instead, I can just add a config file for ``google-music-scripts`` that lets users set defaults for options. Also, I could add a command that lets users list devices and set the default from that list.

**Comment by thebigmunch** [comment]
If you want a sneak peek, check out the master branch and the [latest docs](https://google-music-scripts.readthedocs.io/en/latest/) for the configuration file. Gotta figure out why the latest docs build isn't generating the CLI docs properly on RTD, but the configuration docs are just fine.

**Comment by thebigmunch** [comment]
Right. I forgot about multiple accounts, despite that being something I've used before : P

I'm not sure that's actually possible to do automatically as google-music-scripts can't know the username until the command and params are already parsed by click. Doing it manually would not be something I'd likely do.

I'll have to think about this. It may actually come down to multiple account users having to specify these things themselves. Leveraging shell aliases would alleviate some of the pain there. But it might be unavoidable. We'll see.

**Comment by thebigmunch** [comment]
The main decision is whether to support it through different sections per username in the config file or having config files in different directories for different usernames. Right now, I've implemented the latter as it keeps things simple for the more common use case of only using one account.
