### ISSUE TITLE
Valid FLAC header not found

### ISSUE THREAD

**Issue by replicant0wnz** [thebigmunch/google-music-scripts#44]
Howdy,

When trying to sync today I'm getting the following error:

```bash
~/Music » gms upload -n -vvvv
[2019-08-03 15:33:26] Logging in to Music Manager
[2019-08-03 15:33:27] Logging in to Mobile Client
[2019-08-03 15:33:28] Loading local songs
[2019-08-03 15:33:28] Found 11299 local songs
[2019-08-03 15:33:28] Comparing hashes
[2019-08-03 15:33:28] Loading Google songs with MobileClient
[2019-08-03 15:33:32] Found 9222 Google songs with MobileClient
Traceback (most recent call last):
  File "/usr/local/bin/gms", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.6/dist-packages/google_music_scripts/cli.py", line 968, in run
    args.func(args)
  File "/usr/local/lib/python3.6/dist-packages/google_music_scripts/commands.py", line 405, in do_upload
    if generate_client_id(song) not in google_client_ids:
  File "/usr/local/lib/python3.6/dist-packages/google_music_proto/musicmanager/utils.py", line 21, in generate_client_id
    song = audio_metadata.load(song)
  File "/usr/local/lib/python3.6/dist-packages/audio_metadata/api.py", line 119, in load
    return parser_cls.load(fileobj)
  File "/usr/local/lib/python3.6/dist-packages/audio_metadata/formats/flac.py", line 314, in load
    raise InvalidHeader("Valid FLAC header not found.")
audio_metadata.exceptions.InvalidHeader: Valid FLAC header not found.
```
Not really sure where to go from here as it doesn't specify a single item or anything ..

**Comment by thebigmunch** [comment]
Yeah, I haven't finished adding all the debug log messages I'd like to. Adding a ``print(song)`` right above this:

```
File "/usr/local/lib/python3.6/dist-packages/google_music_scripts/commands.py", line 405, in do_upload
    if generate_client_id(song) not in google_client_ids:
```

will print out each song as it's checking the hash. The last one printed before the failure is the troublemaker. I have a bit of a hunch on what may be going on, but I'd like to see the file to make sure.

**Comment by replicant0wnz** [comment]
That got me past the hump, found some corrupt FLAC files and verified using the `flac` tool. Thanks!

**Comment by thebigmunch** [comment]
I'd still like to get those files if you still have them. Helps my audio-metadata library to test with broken files as much or more as good files.

**Comment by replicant0wnz** [comment]
Threw a single file called `bad.flac` here:

http://dallaslamers.org/flac/

The file itself seems to be corrupt as it won't play. Entire CD is that way, not sure how I got it into my collection :-D 

```bash
dragonstone :: ~ » flac -a bad.flac

flac 1.3.2
Copyright (C) 2000-2009  Josh Coalson, 2011-2016  Xiph.Org Foundation
flac comes with ABSOLUTELY NO WARRANTY.  This is free software, and you are
welcome to redistribute it under certain conditions.  Type `flac' for details.

bad.flac: *** Got error code 0:FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC

The input file is either not a FLAC file or is corrupted.  If you are
convinced it is a FLAC file, you can rerun the same command and add the
-F parameter to try and recover as much as possible from the file.
```

**Comment by thebigmunch** [comment]
Thanks for reporting and for sending that file along. It confirms my hunch. 

That file should not have gotten to the point where it failed where it did. I've refactored the function to determine what a file should be processed as, if anything, in my audio-metadata library a couple times. The last one made it so that if you pass the extension it will force it to be processed as the associated format even if magic signatures aren't found. The google-music-scripts code passes the extension. So, either I need to change the audio-metadata function semantics or change the google-music-scripts code.

**Comment by thebigmunch** [comment]
And now that I read my docs on the extension parameter, I realize that the initial purpose of it is no longer needed due to one of those refactors *facepalm*.

**Comment by replicant0wnz** [comment]
Cool, glad I could help!

FYI, I removed the above link now that ya grabbed the file ..
