### ISSUE TITLE
unable to install 

### ISSUE THREAD

**Issue by jrp13149** [thebigmunch/google-music-scripts#5]
The README says I should type `pip install google-music-scripts`

But this doesn't work. I actually have to use `sudo -H pip install google-music-scripts-master/` to get anywhere. But even then the install fails with:

`Processing ./google-music-scripts-master
  Installing build dependencies ... done
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-021_eqh8/setup.py", line 11, in <module>
        exec(f.read(), about)
      File "<string>", line 24
        __copyright__ = f'2018 {__author__} <{__author_email__}>'
                                                                ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-021_eqh8/
`

I'm not really that familiar with pip. Am I missing something really obvious?

Thanks! 

Jeff.

**Comment by thebigmunch** [comment]
Only Python 3.6+ is supported.

**Comment by jrp13149** [comment]
Doh!

Thanks. Not entirely comfortable with python 3 either!
