### ISSUE TITLE
Supported format signature not found

### ISSUE THREAD

**Issue by adriel** [thebigmunch/google-music-scripts#59]
Like many others, I'm trying to download my music since they're closing.
Any idea what I can do about this error?
Or can I add a flag to skip whatever song it doesn't support.

The command I used:
`gms download ./`

```
Traceback (most recent call last):
  File "/home/user/.local/bin/gms", line 10, in <module>
    sys.exit(run())
  File "/home/user/.local/lib/python3.7/site-packages/google_music_scripts/cli.py", line 618, in run
    args.func(args)
  File "/home/user/.local/lib/python3.7/site-packages/google_music_scripts/commands.py", line 263, in do_download
    download_songs(mm, to_download, template=args.output)
  File "/home/user/.local/lib/python3.7/site-packages/google_music_scripts/core.py", line 51, in download_songs
    tags = audio_metadata.loads(audio).tags
  File "/home/user/.local/lib/python3.7/site-packages/audio_metadata/api.py", line 148, in loads
    raise UnsupportedFormat("Supported format signature not found.")
audio_metadata.exceptions.UnsupportedFormat: Supported format signature not found.
```

I'm re-running the command with `-vvvvv` to see what file it failed at.

**Comment by thebigmunch** [comment]
You can use the code I suggested in the other issue to save the file (it will also skip it) and attach it here or email it to me so I can look at it.

**Comment by adriel** [comment]
Hey, haven't added that code yet, will be re-running it now with the code. But I got the file that it errored on last time, looks like it's a bit of a kinda broken file. So not surprised it errored on it.
Anyway, attached it.

[ - karl jenkins (new album).mp3.mp3.zip](https://github.com/thebigmunch/google-music-scripts/files/4641336/-.karl.jenkins.new.album.mp3.mp3.zip)

**Comment by thebigmunch** [comment]
> Hey, haven't added that code yet, will be re-running it now with the code. But I got the file that it errored on last time, looks like it's a bit of a kinda broken file. So not surprised it errored on it.
> Anyway, attached it.

Indeed. I'm surprised that there was somehow an invalid MP3 file on Google Music. Since that's a possibility, I'll add a try/except with an appropriate failure message in cases like this.
